services:
  database:
    image: postgres:17
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: file_upload
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:4510-4559:4510-4559'
    environment:
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}
      AWS_DEFAULT_REGION: eu-central-1
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db:
    driver: local
  localstack-data:
    driver: local
