services:
  database:
    image: postgres:17
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: file_upload
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
    driver: local
