export enum UploadStatus {
  PENDING = 'PENDING',
  UPLOADED = 'UPLOADED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  DELETED = 'DELETED'
}

export enum MalwareScanStatus {
  NOT_STARTED = 'NOT_STARTED',
  NO_THREATS_FOUND = 'NO_THREATS_FOUND',
  THREATS_FOUND = 'THREATS_FOUND',
  UNSUPPORTED = 'UNSUPPORTED',
  ACCESS_DENIED = 'ACCESS_DENIED',
  FAILED = 'FAILED'
}
